import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { useTranslation } from 'react-i18next';
import { useMutation } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useBooking } from '@/context/booking-context';
import { InsertBooking, InsertPassenger } from '@shared/schema';
import { useToast } from '@/hooks/use-toast';
import { AlertTriangle, Check, ArrowRight, Plane, User, Euro, Calendar } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';

const formatDate = (dateStr: string) => {
  const date = new Date(dateStr);
  return date.toLocaleDateString('en-US', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric'
  });
};

const OverviewPage = () => {
  const { t } = useTranslation();
  const [, navigate] = useLocation();
  const { toast } = useToast();
  const { bookingData, setBooking, setBookingId, setBookingReference } = useBooking();
  const [isRedirecting, setIsRedirecting] = useState(false);
  
  // Redirect if missing necessary data
  useEffect(() => {
    if (!bookingData.selectedFlight || !bookingData.options || !bookingData.passengers || !bookingData.contactInfo) {
      navigate('/search');
    }
  }, [bookingData, navigate]);
  
  // Function to format passenger details into specialRequests string
  const formatPassengerDetails = (existingRequests: string | undefined, passenger?: InsertPassenger): string => {
    let specialRequestsWithPassenger = existingRequests || '';
    
    if (passenger) {
      if (specialRequestsWithPassenger && !specialRequestsWithPassenger.endsWith(',')) {
        specialRequestsWithPassenger += ', ';
      }
      
      specialRequestsWithPassenger += `firstName:${passenger.firstName}, lastName:${passenger.lastName}, title:${passenger.title}`;
      
      if (passenger.nationality) {
        specialRequestsWithPassenger += `, nationality:${passenger.nationality}`;
      }
      
      if (passenger.passportNumber) {
        specialRequestsWithPassenger += `, passportNumber:${passenger.passportNumber}`;
      }
      
      if (bookingData.searchParams?.departureDate) {
        specialRequestsWithPassenger += `, departureDate:${bookingData.searchParams.departureDate}`;
      }
    }
    
    return specialRequestsWithPassenger;
  };
  
  // Create booking mutation
  const createBookingMutation = useMutation({
    mutationFn: async (bookingData: InsertBooking) => {
      const res = await apiRequest('POST', '/api/bookings', bookingData);
      return res.json();
    },
  });
  
  // Initiate Stripe checkout
  const initiateStripeCheckout = async () => {
    try {
      setIsRedirecting(true);
      
      // Check if we have all required data
      if (!bookingData.selectedFlight || !bookingData.options || !bookingData.contactInfo || !bookingData.totalPrice) {
        toast({
          title: t('error_fields'),
          description: 'Missing required booking information',
          variant: 'destructive',
        });
        setIsRedirecting(false);
        return;
      }
      
      // First create the booking
      const bookingToCreate: InsertBooking = {
        userId: 1, // Mock user ID
        flightId: bookingData.selectedFlight.id,
        bookingReference: '', // Will be generated by the server
        totalPrice: bookingData.totalPrice,
        currency: 'EUR', // Use EUR as default currency
        status: 'pending',
        expressProcessing: bookingData.options.expressProcessing,
        editableTicket: bookingData.options.editableTicket,
        hotelReservation: bookingData.options.hotelReservation,
        insuranceLetter: bookingData.options.insuranceLetter,
        contactEmail: bookingData.contactInfo.email,
        contactPhone: bookingData.contactInfo.phone || '',
        travelPurpose: bookingData.searchParams?.travelPurpose || 'visa',
        specialRequests: bookingData.passengers && bookingData.passengers.length > 0 
          ? formatPassengerDetails(bookingData.specialRequests, bookingData.passengers[0])
          : bookingData.specialRequests || '',
      };
      
      const booking = await createBookingMutation.mutateAsync(bookingToCreate);
      setBooking(booking);
      setBookingId(booking.id);
      setBookingReference(booking.bookingReference);
      
      // Create a Stripe payment intent
      const response = await apiRequest('POST', '/api/stripe/create-payment-intent', {
        bookingId: booking.id,
        testMode: false
      });
      
      const paymentData = await response.json();
      
      if (paymentData.success && paymentData.clientSecret) {
        // In a real implementation with Stripe, we would redirect to a Stripe Checkout page
        // For this example, we'll simulate a redirect and then go to confirmation
        
        toast({
          title: t('payment.redirecting'),
          description: t('payment.redirectingToStripe'),
        });
        
        // Simulate redirect to Stripe for payment
        setTimeout(() => {
          // For demo purposes, update the booking status directly
          apiRequest('PATCH', `/api/bookings/${booking.id}`, {
            status: 'confirmed',
            paymentId: 'sim_stripe_' + Date.now()
          }).then(() => {
            navigate(`/confirmation/${booking.id}`);
          });
        }, 3000);
      } else {
        throw new Error(paymentData.message || 'Failed to create payment intent');
      }
      
    } catch (error) {
      setIsRedirecting(false);
      toast({
        title: 'Error initializing payment',
        description: error instanceof Error ? error.message : t('error_server'),
        variant: 'destructive',
      });
    }
  };
  
  // Skip payment and show ticket demo
  const handleSkipPayment = async () => {
    try {
      // Check if we have all required data first
      if (!bookingData.selectedFlight || !bookingData.options || !bookingData.contactInfo || !bookingData.totalPrice) {
        toast({
          title: t('error_fields'),
          description: 'Missing required booking information',
          variant: 'destructive',
        });
        return;
      }
      
      // First create the booking
      const bookingToCreate: InsertBooking = {
        userId: 1, // Mock user ID
        flightId: bookingData.selectedFlight.id,
        bookingReference: '', // Will be generated by the server
        totalPrice: bookingData.totalPrice,
        currency: 'EUR',
        status: 'confirmed', // Directly confirm the booking
        expressProcessing: bookingData.options.expressProcessing,
        editableTicket: bookingData.options.editableTicket,
        hotelReservation: bookingData.options.hotelReservation,
        insuranceLetter: bookingData.options.insuranceLetter,
        contactEmail: bookingData.contactInfo.email,
        contactPhone: bookingData.contactInfo.phone || '',
        travelPurpose: bookingData.searchParams?.travelPurpose || 'visa',
        specialRequests: bookingData.passengers && bookingData.passengers.length > 0 
          ? formatPassengerDetails(bookingData.specialRequests, bookingData.passengers[0])
          : bookingData.specialRequests || '',
      };
      
      const booking = await createBookingMutation.mutateAsync(bookingToCreate);
      setBooking(booking);
      setBookingId(booking.id);
      setBookingReference(booking.bookingReference);
      
      // Skip payment and go straight to confirmation
      navigate(`/confirmation/${booking.id}`);
      
    } catch (error) {
      toast({
        title: 'Error creating booking',
        description: error instanceof Error ? error.message : t('error_server'),
        variant: 'destructive',
      });
    }
  };
  
  // If missing data, show error
  if (!bookingData.selectedFlight || !bookingData.options || !bookingData.passengers || !bookingData.contactInfo || !bookingData.totalPrice) {
    return (
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto text-center">
          <AlertTriangle className="h-12 w-12 text-amber-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-800 mb-2">Missing booking information</h2>
          <p className="text-gray-600 mb-6">Please complete the previous steps first.</p>
          <Button onClick={() => navigate('/search')}>
            Go to Flight Search
          </Button>
        </div>
      </div>
    );
  }
  
  // Format price with currency
  const formatPrice = (price: number, currency = 'EUR') => {
    return `${currency === 'EUR' ? '€' : '$'}${price.toFixed(2)}`;
  };

  return (
    <section className="py-12 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="flex justify-center mb-6">
          <Button 
            onClick={handleSkipPayment}
            className="bg-amber-500 hover:bg-amber-600"
          >
            Skip Payment & View Ticket Demo
          </Button>
        </div>
        
        <div className="max-w-4xl mx-auto mb-8">
          <h1 className="text-3xl font-bold text-center mb-8">{t('overview.title')}</h1>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="md:col-span-2 space-y-6">
              {/* Flight Details */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center">
                    <Plane className="mr-2 h-5 w-5" />
                    {t('overview.flightDetails')}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-col space-y-4">
                    <div className="flex justify-between items-center">
                      <div>
                        <p className="text-sm text-muted-foreground">{t('overview.flight')}</p>
                        <p className="font-medium">{bookingData.selectedFlight.airlineName} {bookingData.selectedFlight.flightNumber}</p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">{t('overview.date')}</p>
                        <p className="font-medium">{formatDate(bookingData.selectedFlight.departureTime)}</p>
                      </div>
                    </div>
                    
                    <div className="flex items-center justify-between">
                      <div className="text-center">
                        <p className="font-bold text-lg">{bookingData.selectedFlight.departureAirport}</p>
                        <p className="text-sm text-muted-foreground">{bookingData.selectedFlight.departureCity}</p>
                        <p className="text-sm">
                          {new Date(bookingData.selectedFlight.departureTime).toLocaleTimeString('en-US', {
                            hour: '2-digit',
                            minute: '2-digit',
                            hour12: false
                          })}
                        </p>
                      </div>
                      
                      <div className="flex-1 flex flex-col items-center mx-4">
                        <div className="w-full flex items-center">
                          <div className="h-0.5 flex-1 bg-gray-300"></div>
                          <ArrowRight className="mx-2 text-gray-400" />
                          <div className="h-0.5 flex-1 bg-gray-300"></div>
                        </div>
                        <span className="text-xs text-muted-foreground mt-1">{bookingData.selectedFlight.duration}</span>
                      </div>
                      
                      <div className="text-center">
                        <p className="font-bold text-lg">{bookingData.selectedFlight.arrivalAirport}</p>
                        <p className="text-sm text-muted-foreground">{bookingData.selectedFlight.arrivalCity}</p>
                        <p className="text-sm">
                          {new Date(bookingData.selectedFlight.arrivalTime).toLocaleTimeString('en-US', {
                            hour: '2-digit',
                            minute: '2-digit',
                            hour12: false
                          })}
                        </p>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              
              {/* Passenger Information */}
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center">
                    <User className="mr-2 h-5 w-5" />
                    {t('overview.passengerInformation')}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  {bookingData.passengers && bookingData.passengers.map((passenger, index) => (
                    <div key={index} className="mb-4 pb-4 border-b border-gray-100 last:border-0 last:mb-0 last:pb-0">
                      <div className="flex justify-between">
                        <div>
                          <p className="text-sm text-muted-foreground">{t('overview.passengerName')}</p>
                          <p className="font-medium">{passenger.title}. {passenger.firstName} {passenger.lastName}</p>
                        </div>
                        <div>
                          <p className="text-sm text-muted-foreground">{t('overview.passportNumber')}</p>
                          <p className="font-medium">{passenger.passportNumber}</p>
                        </div>
                      </div>
                    </div>
                  ))}
                  
                  <div className="mt-4">
                    <h4 className="font-medium mb-2">{t('overview.contactInformation')}</h4>
                    <div className="grid grid-cols-2 gap-4">
                      <div>
                        <p className="text-sm text-muted-foreground">{t('overview.email')}</p>
                        <p>{bookingData.contactInfo.email}</p>
                      </div>
                      <div>
                        <p className="text-sm text-muted-foreground">{t('overview.phone')}</p>
                        <p>{bookingData.contactInfo.phone || t('overview.notProvided')}</p>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
            
            {/* Order Summary */}
            <div>
              <Card className="sticky top-4">
                <CardHeader>
                  <CardTitle className="flex items-center">
                    <Euro className="mr-2 h-5 w-5" />
                    {t('overview.orderSummary')}
                  </CardTitle>
                  <CardDescription>
                    {t('overview.priceBreakdown')}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    <div className="flex justify-between">
                      <span>{t('overview.baseFare')}</span>
                      <span>{formatPrice(bookingData.selectedFlight.basePrice)}</span>
                    </div>
                    
                    {bookingData.options.expressProcessing && (
                      <div className="flex justify-between">
                        <span>{t('option_express_title')}</span>
                        <span>{formatPrice(2)}</span>
                      </div>
                    )}
                    
                    {bookingData.options.editableTicket && (
                      <div className="flex justify-between">
                        <span>{t('option_editable_title')}</span>
                        <span>{formatPrice(2)}</span>
                      </div>
                    )}
                    
                    {bookingData.options.hotelReservation && (
                      <div className="flex justify-between">
                        <span>{t('option_hotel_title')}</span>
                        <span>{formatPrice(2)}</span>
                      </div>
                    )}
                    
                    {bookingData.options.insuranceLetter && (
                      <div className="flex justify-between">
                        <span>{t('option_insurance_title')}</span>
                        <span>{formatPrice(2)}</span>
                      </div>
                    )}
                    
                    <Separator />
                    
                    <div className="flex justify-between font-bold">
                      <span>{t('summary_total')}</span>
                      <span>{formatPrice(bookingData.totalPrice)}</span>
                    </div>
                  </div>
                </CardContent>
                <CardFooter>
                  <Button 
                    className="w-full"
                    onClick={initiateStripeCheckout}
                    disabled={isRedirecting || createBookingMutation.isPending}
                  >
                    {isRedirecting ? (
                      <>
                        <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        {t('overview.redirecting')}
                      </>
                    ) : (
                      <>
                        {t('overview.proceedToCheckout')}
                      </>
                    )}
                  </Button>
                </CardFooter>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default OverviewPage;