import { useEffect, useState } from 'react';
import { useLocation } from 'wouter';
import { useTranslation } from 'react-i18next';
import { useMutation } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useBooking } from '@/context/booking-context';
import { Payment, InsertBooking, InsertPassenger } from '@shared/schema';
import PaymentForm from '@/components/ui/payment-form';
import { StripePaymentForm } from '@/components/ui/stripe-payment-form';
import { useToast } from '@/hooks/use-toast';
import { AlertTriangle, Check, CreditCard } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

const PaymentPage = () => {
  const { t } = useTranslation();
  const [, navigate] = useLocation();
  const { toast } = useToast();
  const { bookingData, setBooking, setBookingId, setBookingReference } = useBooking();
  
  // Redirect if missing necessary data
  useEffect(() => {
    if (!bookingData.selectedFlight || !bookingData.options || !bookingData.passengers || !bookingData.contactInfo) {
      navigate('/search');
    }
  }, [bookingData, navigate]);
  
  // Function to format passenger details into specialRequests string
  const formatPassengerDetails = (existingRequests: string | undefined, passenger?: InsertPassenger): string => {
    // If we have a departure date from the search params, include it
    let specialRequestsWithPassenger = existingRequests || '';
    
    // Add passenger details to special requests
    if (passenger) {
      // Start with a comma if there are existing requests
      if (specialRequestsWithPassenger && !specialRequestsWithPassenger.endsWith(',')) {
        specialRequestsWithPassenger += ', ';
      }
      
      // Add passenger details (removed title as it doesn't exist in database schema)
      specialRequestsWithPassenger += `firstName:${passenger.firstName}, lastName:${passenger.lastName}`;
      
      // Add additional passenger details if present
      if (passenger.nationality) {
        specialRequestsWithPassenger += `, nationality:${passenger.nationality}`;
      }
      
      if (passenger.passportNumber) {
        specialRequestsWithPassenger += `, passportNumber:${passenger.passportNumber}`;
      }
      
      // Include departure date from search parameters if available
      if (bookingData.searchParams?.departureDate) {
        specialRequestsWithPassenger += `, departureDate:${bookingData.searchParams.departureDate}`;
      }
    }
    
    return specialRequestsWithPassenger;
  };
  
  // Create booking mutation
  const createBookingMutation = useMutation({
    mutationFn: async (bookingData: InsertBooking) => {
      const res = await apiRequest('POST', '/api/bookings', bookingData);
      return res.json();
    },
  });
  
  // Process payment mutation
  const processPaymentMutation = useMutation({
    mutationFn: async ({ payment, bookingId }: { payment: Payment, bookingId: number }) => {
      const res = await apiRequest('POST', '/api/payments', {
        ...payment,
        bookingId
      });
      return res.json();
    },
    onSuccess: (data, variables) => {
      if (data.success) {
        // Use the booking ID passed in the variables instead of relying on createBookingMutation.data
        navigate(`/confirmation/${variables.bookingId}`);
      } else {
        toast({
          title: t('error_payment_failed'),
          description: data.message,
          variant: 'destructive',
        });
      }
    },
    onError: (error) => {
      toast({
        title: t('error_payment_failed'),
        description: error instanceof Error ? error.message : t('error_server'),
        variant: 'destructive',
      });
    }
  });
  
  // Handle payment submission
  const handlePaymentComplete = async (paymentData: Payment) => {
    // Check if we have all required data
    if (!bookingData.selectedFlight || !bookingData.options || !bookingData.contactInfo || !bookingData.totalPrice) {
      toast({
        title: t('error_fields'),
        description: 'Missing required booking information',
        variant: 'destructive',
      });
      return;
    }
    
    try {
      // Log contact info to debug
      console.log('Creating booking with contact info:', JSON.stringify(bookingData.contactInfo));
      
      // First create the booking
      const bookingToCreate: InsertBooking = {
        userId: 1, // Mock user ID
        flightId: bookingData.selectedFlight.id,
        bookingReference: '', // Will be generated by the server
        totalPrice: bookingData.totalPrice,
        currency: 'USD',
        status: 'pending',
        expressProcessing: bookingData.options.expressProcessing,
        editableTicket: bookingData.options.editableTicket,
        hotelReservation: bookingData.options.hotelReservation,
        insuranceLetter: bookingData.options.insuranceLetter,
        contactEmail: bookingData.contactInfo.email,
        contactPhone: bookingData.contactInfo.phone || '', // Ensure contactPhone is never undefined
        travelPurpose: bookingData.searchParams?.travelPurpose || 'visa',
        specialRequests: bookingData.passengers && bookingData.passengers.length > 0 
          ? formatPassengerDetails(bookingData.specialRequests, bookingData.passengers[0])
          : bookingData.specialRequests || '',
      };
      
      const booking = await createBookingMutation.mutateAsync(bookingToCreate);
      setBooking(booking);
      setBookingId(booking.id);
      setBookingReference(booking.bookingReference);
      
      // Now process payment
      await processPaymentMutation.mutateAsync({
        payment: paymentData,
        bookingId: booking.id
      });
      
    } catch (error) {
      toast({
        title: 'Error creating booking',
        description: error instanceof Error ? error.message : t('error_server'),
        variant: 'destructive',
      });
    }
  };
  
  // If missing data, show error
  if (!bookingData.selectedFlight || !bookingData.options || !bookingData.passengers || !bookingData.contactInfo || !bookingData.totalPrice) {
    return (
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto text-center">
          <AlertTriangle className="h-12 w-12 text-amber-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-gray-800 mb-2">Missing booking information</h2>
          <p className="text-gray-600 mb-6">Please complete the previous steps first.</p>
          <Button onClick={() => navigate('/search')}>
            Go to Flight Search
          </Button>
        </div>
      </div>
    );
  }
  
  // Skip payment and show ticket demo
  const handleSkipPayment = async () => {
    try {
      // Check if we have all required data first
      if (!bookingData.selectedFlight || !bookingData.options || !bookingData.contactInfo || !bookingData.totalPrice) {
        toast({
          title: t('error_fields'),
          description: 'Missing required booking information',
          variant: 'destructive',
        });
        return;
      }
      
      // Log contact info to debug
      console.log('Skip Payment: Creating booking with contact info:', JSON.stringify(bookingData.contactInfo));
      
      // First create the booking
      const bookingToCreate: InsertBooking = {
        userId: 1, // Mock user ID
        flightId: bookingData.selectedFlight.id,
        bookingReference: '', // Will be generated by the server
        totalPrice: bookingData.totalPrice,
        currency: 'USD',
        status: 'confirmed', // Directly confirm the booking
        expressProcessing: bookingData.options.expressProcessing,
        editableTicket: bookingData.options.editableTicket,
        hotelReservation: bookingData.options.hotelReservation,
        insuranceLetter: bookingData.options.insuranceLetter,
        contactEmail: bookingData.contactInfo.email,
        contactPhone: bookingData.contactInfo.phone || '', // Ensure contactPhone is never undefined
        travelPurpose: bookingData.searchParams?.travelPurpose || 'visa',
        specialRequests: bookingData.passengers && bookingData.passengers.length > 0 
          ? formatPassengerDetails(bookingData.specialRequests, bookingData.passengers[0])
          : bookingData.specialRequests || '',
      };
      
      const booking = await createBookingMutation.mutateAsync(bookingToCreate);
      setBooking(booking);
      setBookingId(booking.id);
      setBookingReference(booking.bookingReference);
      
      // Skip payment and go straight to confirmation
      navigate(`/confirmation/${booking.id}`);
      
    } catch (error) {
      toast({
        title: 'Error creating booking',
        description: error instanceof Error ? error.message : t('error_server'),
        variant: 'destructive',
      });
    }
  };

  // Handle Stripe payment completion
  const handleStripePaymentComplete = async (paymentId: string, status: string) => {
    // Check if we have all required data
    if (!bookingData.selectedFlight || !bookingData.options || !bookingData.contactInfo || !bookingData.totalPrice) {
      toast({
        title: t('error_fields'),
        description: 'Missing required booking information',
        variant: 'destructive',
      });
      return;
    }
    
    try {
      // First create the booking
      const bookingToCreate: InsertBooking = {
        userId: 1, // Mock user ID
        flightId: bookingData.selectedFlight.id,
        bookingReference: '', // Will be generated by the server
        totalPrice: bookingData.totalPrice,
        currency: 'EUR', // Use EUR as default currency
        status: 'pending',
        expressProcessing: bookingData.options.expressProcessing,
        editableTicket: bookingData.options.editableTicket,
        hotelReservation: bookingData.options.hotelReservation,
        insuranceLetter: bookingData.options.insuranceLetter,
        contactEmail: bookingData.contactInfo.email,
        contactPhone: bookingData.contactInfo.phone || '',
        travelPurpose: bookingData.searchParams?.travelPurpose || 'visa',
        specialRequests: bookingData.passengers && bookingData.passengers.length > 0 
          ? formatPassengerDetails(bookingData.specialRequests, bookingData.passengers[0])
          : bookingData.specialRequests || '',
      };
      
      const booking = await createBookingMutation.mutateAsync(bookingToCreate);
      setBooking(booking);
      setBookingId(booking.id);
      setBookingReference(booking.bookingReference);
      
      // Update booking with payment info
      await apiRequest('PATCH', `/api/bookings/${booking.id}`, {
        status: 'confirmed',
        paymentId: paymentId
      });
      
      // Navigate to confirmation page
      navigate(`/confirmation/${booking.id}`);
      
    } catch (error) {
      toast({
        title: 'Error finalizing booking',
        description: error instanceof Error ? error.message : t('error_server'),
        variant: 'destructive',
      });
    }
  };

  return (
    <section className="py-12 bg-gray-50">
      <div className="container mx-auto px-4">
        <div className="flex justify-center mb-6">
          <Button 
            onClick={handleSkipPayment}
            className="bg-amber-500 hover:bg-amber-600"
          >
            Skip Payment & View Ticket Demo
          </Button>
        </div>
        
        <div className="max-w-4xl mx-auto mb-8">
          <h1 className="text-3xl font-bold text-center mb-8">{t('payment.chooseMethod')}</h1>
          
          <Tabs defaultValue="stripe" className="w-full">
            <TabsList className="grid w-full grid-cols-2 mb-8">
              <TabsTrigger value="stripe" className="flex items-center justify-center gap-2">
                <CreditCard className="h-4 w-4" />
                {t('payment.stripePayment')}
              </TabsTrigger>
              <TabsTrigger value="standard" className="flex items-center justify-center gap-2">
                <Check className="h-4 w-4" />
                {t('payment.standardPayment')}
              </TabsTrigger>
            </TabsList>
            
            <TabsContent value="stripe" className="mt-0">
              <StripePaymentForm 
                bookingId={-1} // This is just a placeholder, will be replaced when booking is created
                amount={bookingData.totalPrice!}
                currency="EUR"
                onPaymentComplete={handleStripePaymentComplete}
              />
            </TabsContent>
            
            <TabsContent value="standard" className="mt-0">
              <PaymentForm 
                flight={bookingData.selectedFlight!}
                totalPrice={bookingData.totalPrice!}
                options={bookingData.options!}
                onPaymentComplete={handlePaymentComplete}
                isProcessing={createBookingMutation.isPending || processPaymentMutation.isPending}
              />
            </TabsContent>
          </Tabs>
        </div>
      </div>
    </section>
  );
};

export default PaymentPage;
